[project]
name = "nerfbridge"
version = "0.1"

dependencies = [
	"nerfstudio==0.3.3"
]

[tool.setuptools.packages.find]
include = ["nerfbridge*"]

[tool.pyright]
extraPaths = ["nerfbridge"]

[project.entry-points.'nerfstudio.method_configs']
ros-nerfacto = 'nerfbridge.method_configs:RosNerfacto'
ros-depth-nerfacto = 'nerfbridge.method_configs:RosDepthNerfacto'
nerfbridge-demo = 'nerfbridge.method_configs:NerfBridgeDemo'
depth-nerfbridge-demo = 'nerfbridge.method_configs:DepthNerfBridgeDemo'
